import StoreProvider from './StoreProvider'
import './globals.scss'
import { inter, roboto } from './fonts/fonts.js'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import Link from 'next/link'
import Head from 'next/head'

export const metadata = {
  title: 'My Clothing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="uk" className={`${inter.variable} ${roboto.variable}`}>
      {/* <Head>
        <link rel="shortcut icon" href="" />
      </Head> */}
      <body>
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
