import StoreProvider from "./StoreProvider";
import "./globals.scss";
import { inter, roboto } from "./fonts/fonts.js";

export const metadata = {
  title: "My Clothing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk" className={`${inter.variable} ${roboto.variable}`}>
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
